import { readFile } from "node:fs/promises";
import path from "node:path";

/**
 * Server-only. The built registry JSON at public/r/<slug>.json is the single
 * source of truth for a component's install command, npm deps, and full source.
 * It is generated by `pnpm registry:build` (which runs before `next build`),
 * so this fs read resolves at build/prerender time.
 */

export type RegistrySource = {
  /** the full component source, ready to paste into components/motion/<slug>.tsx */
  source: string;
  /** repo-relative target path the file lands at */
  targetPath: string;
  /** npm runtime deps (e.g. ["motion"]) */
  dependencies: string[];
  /** other registry items this one pulls in (e.g. the provider) */
  registryDependencies: string[];
  /** the `npx shadcn add …` command for this slug */
  installCommand: string;
};

type RegistryFile = {
  path: string;
  content?: string;
  target?: string;
  type?: string;
};

type RegistryItem = {
  files?: RegistryFile[];
  dependencies?: string[];
  registryDependencies?: string[];
};

/** The public origin the registry is served from — used for install commands. */
export const REGISTRY_ORIGIN = "https://motion.asmitsah.dev";

export function installCommandFor(slug: string): string {
  return `npx shadcn add ${REGISTRY_ORIGIN}/r/${slug}.json`;
}

export async function getRegistrySource(slug: string): Promise<RegistrySource | null> {
  const jsonPath = path.join(process.cwd(), "public", "r", `${slug}.json`);
  try {
    const raw = await readFile(jsonPath, "utf8");
    const item = JSON.parse(raw) as RegistryItem;
    const files = item.files ?? [];
    // Prefer the file that lands at components/motion/<slug>.tsx; else the first.
    const primary = files.find((f) => f.path === `components/motion/${slug}.tsx`) ?? files[0];

    if (!primary?.content) return null;

    return {
      source: primary.content,
      targetPath: primary.path,
      dependencies: item.dependencies ?? [],
      registryDependencies: item.registryDependencies ?? [],
      installCommand: installCommandFor(slug),
    };
  } catch {
    // Missing or malformed registry JSON — degrade gracefully rather than
    // crashing the build (e.g. a half-written file during `registry:build`).
    return null;
  }
}
